artifact_location: /workspaces/mlops-project/02-experiment-tracking/homework/db_type:/path_to_db/0
creation_time: 1716982859594
experiment_id: '0'
last_update_time: 1716982859594
lifecycle_stage: active
name: Default
